// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct ComputeData
{
    float4 q;
};

AppendStructuredBuffer<ComputeData> dataBuffer;
RWStructuredBuffer<int> argsBuffer;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int size = 10000;
    for (int i = 0; i < size; i++)
    {
        ComputeData test;
        test.q = float4(1, 2, 3, 4);
        dataBuffer.Append(test);
    }
    
    argsBuffer[0] = size;
}
